x-includes:
  webserver-template: "compose-shared-apache.yml"
  database-template: "compose-shared-mariadb.yml"

services:
  mysql:
    image: mariadb:10.6
  openemr:
    image: openemr/openemr:flex-3.21
